### PR TITLE
These two filters enhance the user image. One is in grayscale which provides better line definitions and outlines while the other is in colour and it provides better clarity and brightness

### PR DESCRIPTION
**Pull request by PBnoJ273**

### CODE REVIEW

**Comment by Davidy22** [comment]
It's ok to send these one by one when they're ready, I can merge them individually, don't need to keep pulling these back for the mega PR that I presume you're prepping

**Comment by PBnoJ273** [comment]
Sounds good! Thank you! We needed to give the one mega PR for a course my team and I are taking. Thanks again!

**Comment by Davidy22** [comment]
Oh, is this for university or something?

**Comment by PBnoJ273** [comment]
Yeah, it’s a final project for a university course. The goals is to find a cool open source project and contribute to it.

**Pull request closed without merging**
